# Generated by Django 5.1.1 on 2025-10-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='profession',
            field=models.CharField(blank=True, choices=[('psychologist', 'Psicóloga'), ('psychopedagogist', 'Psicopedagoga')], max_length=32, verbose_name='área de atuação'),
        ),
    ]
