# Generated by Django 5.1.1 on 2025-10-08 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_alter_professional_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responses', models.JSONField(default=list)),
                ('score_total', models.FloatField()),
                ('functional_level', models.CharField(choices=[('severe', 'Grave'), ('moderate', 'Moderado'), ('mild', 'Leve')], max_length=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_assessments', to='clinical.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
