# Generated by Django 5.1.1 on 2025-10-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_diagnosticassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='school_history_file',
            field=models.FileField(blank=True, null=True, upload_to='school_history/'),
        ),
    ]
