# Generated by Django 5.1.1 on 2025-10-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_patient_school_history_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapeuticplan',
            name='review_reminder_sent_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
