version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: teacare
      POSTGRES_PASSWORD: teacare
      POSTGRES_DB: teacare
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgres://teacare:teacare@db:5432/teacare
      DEBUG: "False"
      ALLOWED_HOSTS: localhost,127.0.0.1
      CORS_ALLOWED_ORIGINS: http://localhost:5173,http://localhost:3000
      CSRF_TRUSTED_ORIGINS: http://localhost:5173,http://localhost:3000
      SECRET_KEY: changeme-in-production
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    environment:
      API_BASE_URL: http://localhost:8000/api
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
