services:
  - type: web
    name: sistema-chamados
    env: python
    rootDir: backend

    buildCommand: |
      cd ../frontend
      npm install
      npm run build
      cd ../backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn core.wsgi:application

    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-chamados-db
          property: connectionString

databases:
  - name: sistema-chamados-db
    databaseName: sistema_chamados_db
    user: postgres
    plan: free
    region: oregon
    version: "15"
    extensions:
      - name: pgcrypto
    backupSchedule:
      interval: daily
      time: "02:00"
      retention: 7
    highAvailability: false
    sslEnforcement: true
    maintenanceWindow:
      dayOfWeek: sunday
      startHour: 0
      duration: 60
    autoMinorVersionUpgrade: true
    requireClientCertificates: false
    connectionPooler:
      enabled: false
      poolerType: pgbouncer
      poolerPlan: hobby-dev
    readReplicas:
      enabled: false
    followTheLeader:
      enabled: false
    dataEncryptionAtRest: false
    dataEncryptionInTransit: true
    performanceInsights:
      enabled: false
    tags:
      environment: production
      project: sistema-chamados
