services:
  - type: web
    name: sistema-chamados
    env: python
    buildCommand: |
      cd frontend
      npm install
      npm run build
      cd ..
      pip install -r backend/requirements.txt
      cd backend
      python manage.py collectstatic --noinput

    startCommand: bash start.sh

    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-chamados-db
          property: connectionString

databases:
  - name: sistema-chamados-db
    plan: free
